language: r
sudo: false

cache:
  packages: true
  directories:
    - $HOME/.wekafiles

env:
  global:
    - _R_CHECK_TIMINGS_=0
    - _R_CHECK_FORCE_SUGGESTS_=0
    - secure: "WFbdUIQRi7VYUHceKrg9xnw7m+8SK658rmgWPW++zWq5J4n0ZLuTRdKHu7ijyK9zOzNGjLF+NzvnwPS+yMPJwTX/s82hrC5GAMrYs3shEvR95PwFx42nfjqU5fsKsZ9gYpqIuZoJs32yPOJ/9XBLHU8rUv5+x4Z1zM2hBJHAn74="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
  packages:
    - gcc-4.8
    - g++-4.8
    - libgmp-dev

r_github_packages:
  - berndbischl/BBmisc
  - berndbischl/parallelMap
  - berndbischl/ParamHelpers

before_install:
  - Rscript -e 'install.packages("nlme")'

before_script:
  - java -cp $HOME/R/Library/RWekajars/java/weka.jar weka.core.WekaPackageManager -install-package thirdparty/XMeans1.0.4.zip


notifications:
  email:
    recipients:
        - michellang@gmail.com
